import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import MyComponent from "./layouts/Mycomponent";
config.autoAddCss = false;
// import "./globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rikkei Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <MyComponent></MyComponent>
        <Footer />
      </body>
    </html>
  );
}
